### ISSUE TITLE
No such file or directory: 'data/audio/X_train.npy'

### ISSUE THREAD

**Issue by wuqing778** [talhanai/redbud-tree-depression#6]
Hello, when I surfaced your code, I found No such file: No such file or directory: 'data/audio/ x_train.npy '. May I ask what file it is and how it was generated

**Comment by talhanai** [comment]
`data/audio/x_train.npy` is data used for training the model. You'll have to follow the description in [this paper](https://groups.csail.mit.edu/sls/publications/2018/Alhanai_Interspeech-2018.pdf) to generate the training data.

**Comment by wuqing778** [comment]
> `data/audio/x_train.npy`是用于训练模型的数据。你必须遵循描述[本文](https://groups.csail.mit.edu/sls/publications/2018/Alhanai_Interspeech-2018.pdf)生成训练数据。

Hello, is there any code to generate training data, or do you want to write your own code according to your article
